### ISSUE TITLE
How can i Deploy the local web pages in the package.json?

### ISSUE THREAD

**Issue by masqueradeone** [thekamalkashyap/kamalkashyap.vercel.app#1]
I looked up the answer before asking, but they were not work

**Comment by thekamalkashyap** [comment]
I can't understand your question. would you explain it a bit and sorry for replying you late.

**Comment by masqueradeone** [comment]
I wanne ask about that what should i do if  link the document which type of the HTML,my email seem not working with computer and feel sorry

**Comment by thekamalkashyap** [comment]
i apologize but i still can't get it are you trying to give link to your email address ?

**Comment by thekamalkashyap** [comment]
wait wait are to trying to add html pages to the website ?

**Comment by masqueradeone** [comment]
yep,Static Pages.

**Comment by masqueradeone** [comment]
I try to resolve it and I looked up the answer before asking, but........（in fact,i konw  it may be a simple question and i cannt resolve it）

**Comment by thekamalkashyap** [comment]
if they are `.html` files you need to convert them into `.jsx` files and if they are `.jsx` files simply move them to `src/pages/`. if you want i can show you how to convert html file to jsx or tsx by converting one of your file to jsx. 😊

**Comment by masqueradeone** [comment]
That's great. Thank you so much.    I've been trying to convert them into .jsx files on online sites and move them to src/pages/.   Then,i try to change the code from projectsData.json: "href": "https://XXXXX" to ""href": "../111.jsx",still no working........maby i should more help or learn.I'm sorry to trouble you.

**Comment by masqueradeone** [comment]
I hope you will show it,thanks

**Comment by thekamalkashyap** [comment]
okay so here is how to convert html file to jsx.
lets say your html file is
```
<body>
<p>hello world</p>
<button>this is a button</button>
<div>this is a div </div>
</body>
```
and you want to add lets say a page named `kamal` or any name you want  to website then simply add
```
export default function Kamal(){
return(<>
<p>hello world</p>
<button>this is a button</button>
<div>this is a div </div>
</>)
}
```
this to you a file named `kamal.jsx` and move it to 
`src/pages/`
thats all.
now run `yarn dev` and visit `localhost:3000/kamal`
in your browser and it will show up their 😊

**Comment by masqueradeone** [comment]
Many thanks,i will try it!thanks again

**Comment by thekamalkashyap** [comment]
my pleasure
